# Generated by Django 4.1.7 on 2023-03-19 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_pets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pets',
            name='appointments',
        ),
        migrations.AddField(
            model_name='appointments',
            name='pets',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.pets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pets',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pets',
            name='type',
            field=models.CharField(choices=[('D', 'Dog'), ('C', 'Cat')], max_length=2),
        ),
    ]
