# Generated by Django 4.1.7 on 2023-03-18 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_pets_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pets',
            name='appointments',
        ),
        migrations.AddField(
            model_name='appointments',
            name='pets',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.pets'),
            preserve_default=False,
        ),
    ]
