# Generated by Django 4.1.7 on 2023-03-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_service_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='review',
        ),
    ]
