# Generated by Django 4.1.7 on 2023-03-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_reviews_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
